[advisories]
unmaintained = "deny"
yanked = "deny"
notice = "deny"
unsound = "deny"

[licenses]
allow-osi-fsf-free = "either"

[bans]
multiple-versions = "deny"
wildcards = "allow"
skip = [
  { name = "bitflags", version = "2.0" },
  { name = "event-listener", version = "<5.0" },
  { name = "event-listener-strategy", version = "0.5" },
  { name = "objc-sys", version = "0.2.0-beta.2" },
  { name = "objc2", version = "0.3.0-beta.3.patch-leaks.3" },
  { name = "objc2-encode", version = "2.0.0-pre.2" },
  { name = "redox_syscall", version = "0.3" },
  { name = "regex-automata", version = "0.1" },
  { name = "regex-syntax", version = "0.6" },
  { name = "syn", version = "1.0" },
  { name = "tracing-log", version = "0.1" },
  { name = "windows" },
  { name = "windows-sys" },
  { name = "windows-targets" },
  { name = "windows_aarch64_gnullvm" },
  { name = "windows_aarch64_msvc" },
  { name = "windows_i686_gnu" },
  { name = "windows_i686_msvc" },
  { name = "windows_x86_64_gnu" },
  { name = "windows_x86_64_gnullvm" },
  { name = "windows_x86_64_msvc" },
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"
